name: Test github actions
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - "18.0"

env:
  ENVGHT: ${{ secrets.GITHUB_TOKEN }}
  ENVGHU: ${{ github.token }}
  VARAAA: ${{ vars.AAA }}
  SECBBB: ${{ secrets.BBB }}
  VARREPORGCCC: ${{ vars.CCC }}
  ENVFIX: "abc"

jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: |
          echo "Run action by ${{ github.actor }}"        
          echo "github.token=${{ github.token }}"
          echo "secrets.GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
          echo "GITHUB_EVENT_PATH=$GITHUB_EVENT_PATH"
          echo "repo-token: ${{secrets.GITHUB_TOKEN}}"
          echo "variable org: ${{vars.AAA}}"
          echo "env prg: ${{env.AAA}}"
          echo "env prg: ${{env.VARAAA}}"
          echo "secret org: ${{secrets.BBB}}"
          echo "variable repository of orga: ${{vars.CCC}}"
          echo "ENVGHT: ${{env.ENVGHT}}"
          echo "ENVGHU: ${{env.ENVGHU}}"
          echo "VARAAA: ${{vars.AAA}}"
          echo "ENVAAA: ${{env.VARAAA}}"
          echo "VARREPORGCCC: ${{env.VARREPORGCCC}}"
          echo "ENVFIX: ${{env.ENVFIX}}"
